services:
  - type: web
    name: backend_audio
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install torch==2.2.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
